### ISSUE TITLE
All the links in README.md are pointing to the wrong website

### ISSUE THREAD

**Issue by enigne** [SciML/SciMLTutorialsOutput#1]
Hi, I noticed that all the links in README.md are pointing to http://tutorials.juliadiffeq.org, which also make the links in the website https://tutorials.sciml.ai pointing to the wrong server. Could you please fix this?

**Comment by ChrisRackauckas** [comment]
@staticfloat I updated them on SciMLTutorials.jl though, do you know why it's not pushing the README over?
